import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    // トップページ (index.md) をサイドバーの先頭に表示
    'index', 
    
    // 「過月訂正」カテゴリ
    {
      type: 'category',
      label: '過月訂正',
      // '過月訂正' フォルダの中身を自動で読み込む
      items: [{type: 'autogenerated', dirName: '過月訂正'}],
    },

    // 「売上取消」カテゴリ
    {
      type: 'category',
      label: '売上取消',
      // '売上取消' フォルダの中身を自動で読み込む
      items: [{type: 'autogenerated', dirName: '売上取消'}],
    },

    // 「月途中の変更」カテゴリ
    {
      type: 'category',
      label: '月途中の変更',
      // '月途中の変更' フォルダの中身を自動で読み込む
      items: [{type: 'autogenerated', dirName: '月途中の変更'}],
    },

    // 「入金登録」カテゴリ
    {
      type: 'category',
      label: '入金登録',
      // '入金登録' フォルダの中身を自動で読み込む
      items: [{type: 'autogenerated', dirName: '入金登録'}],
    },

    // 「返金処理」カテゴリ
    {
      type: 'category',
      label: '返金処理',
      // '返金処理' フォルダの中身を自動で読み込む
      items: [{type: 'autogenerated', dirName: '返金処理'}],
    },
  ],
};

export default sidebars;